version: "3.8"

services:
  vm1-app:
    build:
      context: ./vm1-app
    container_name: vm1-app
    volumes:
      - kafka-audit-logs:/app/logs:ro
    networks:
      - kafka-net
    stdin_open: true
    tty: true

  vm2-app:
    build:
      context: ./vm2-app
    container_name: vm2-app
    volumes:
      - kafka-audit-logs:/app/logs:ro
    networks:
      - kafka-net
    stdin_open: true
    tty: true

  vm3-app:
    build:
      context: ./vm3-app
    container_name: vm3-app
    volumes:
      - kafka-audit-logs:/app/logs
    networks:
      - kafka-net
    stdin_open: true
    tty: true

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

volumes:
  kafka-audit-logs:

networks:
  kafka-net: